### ISSUE TITLE
Reading multiple columns of Bigtable to a map in Pig

### ISSUE THREAD

**Issue by anuchandran** [GoogleCloudPlatform/cloud-bigtable-client#1481]
Currently we are using below query for loading data in HBase to Pig for further processing.

sample_data = LOAD 'hbase://test_bigtable' USING org.apache.pig.backend.hadoop.hbase.HBaseStorage('f:id,f:attributes.*’, '-loadKey true') AS (rowkey chararray,id:chararray,attributes;map[]);

With f:attributes.* in the above statement, it was quite convenient to get all the columns like f:attributes.id,f:attributes.name etc as a map.In a real scenario, there could be hundreds of columns,  with f:attributes. prefix , so it is practically impossible to write each and every column in the query.

But this feature does not seem to work with  Dataproc Pig, when I try this,  I am getting below error.

Caused by: com.google.cloud.bigtable.hbase.adapters.filters.UnsupportedFilterException: Unsupported filters encountered: FilterSupportStatus{isSupported=false, reason=
 'Don't know how to adapt Filter class 'class org.apache.hadoop.hbase.filter.FamilyFilter''}, FilterSupportStatus{isSupported=false, reason='Don't know how to adapt Filter class 'class org.apache.hadoop.hbase.filter.FamilyFilter''}

As per Google documentation, FamilyFilter and ColumnPrefixFilter are currently supported.(Reference https://cloud.google.com/bigtable/docs/hbase-differences) But it is quite strange that we are getting a UnsupportedFilterException.
(https://issuetracker.google.com/issues/64749631)

It would be great if you can include a feature to support this.

Thanks in advance,
Anupriya

**Comment by sduskis** [comment]
They both are supported, so this message is indeed strange.  Are you using the latest client?  If so, are you using the bigtable-hbase-1.x-hadoop artifact?

**Comment by anuchandran** [comment]
Yes, I am using below property in hbase-site.xml,

<property>
   <name>hbase.client.connection.impl</name>
   <value>com.google.cloud.bigtable.hbase1_2.BigtableConnection</value>
 </property>

And I am using artifacts of version 0.9.5.1 from http://repo1.maven.org/maven2/com/google/cloud/bigtable/bigtable-hbase-mapreduce/0.9.5.1/.
Is this a very old version ?

**Comment by sduskis** [comment]
We added support for FamilyFilter in 0.9.7.  I would suggest upgrading to the 1.0.0-pre2 version, and using the bigtable-hbase-1.x-hadoop artifact instead of bigtable-hbase-1.2.

**Comment by igorbernstein2** [comment]
When upgrading, please note that the packaging has changed. You can find a description of the new package in the [readme](https://github.com/GoogleCloudPlatform/cloud-bigtable-client#using-the-java-client). In short, if you are accessing bigtable from a hadoop environment, please use `bigtable-hbase-1.x-hadoop`, otherwise please use `bigtable-hbase-1.x`. Also, you will need to update `hbase.client.connection.impl`  to `com.google.cloud.bigtable.hbase1_x.BigtableConnection`.

**Comment by anuchandran** [comment]
Thanks for your replies. I tried with 1.0.0-pre2 version and bigtable-hbase-1.x-hadoop artifact ,
and it worked like a charm :) I would like to understand why it is 1_x , instead of mentioning correct version.

**Comment by sduskis** [comment]
It turns out that a single bigtable-hbase artifact can work with hbase 1.0 -> 1.*, with the exception of the hbase shell which uses ruby.  We opted for a simpler artifact structure in terms of hbase versions that will allow us to do more interesting things with our hbase dependencies.  

Historically We had to do some package renaming to get everything to work well, but the package renaming came with some serious negative implications.  The plain bigtable-hbase-1.x does not perform Bigtable related package renaming, but rather using a shaded hbase-client so that applications like Dataflow are cleaner.  The 1.x-hadoop artifact performs the old style shading in order to work well with a hadoop ecosystem.
