### ISSUE TITLE
CheckAndMutate silently ignores condition for null values

### ISSUE THREAD

**Issue by igorbernstein2** [GoogleCloudPlatform/cloud-bigtable-client#1704]
Extracted from https://github.com/GoogleCloudPlatform/google-cloud-go/issues/621.

It seems like https://github.com/GoogleCloudPlatform/cloud-bigtable-client/blob/5c3ee47e208b4efbfaa5badceff8b403c02cb6d4/bigtable-hbase-parent/bigtable-hbase/src/main/java/com/google/cloud/bigtable/hbase/adapters/CheckAndMutateUtil.java#L113

will replace the condition as always true for comparisons that involve `null`

**Comment by sduskis** [comment]
GoogleCloudPlatform/google-cloud-go#621 talks about an operator other than '==' or '!=' with a null value.  We should run some tests to see what HBase does with other operators, and do the same.

**Comment by sduskis** [comment]
I think that there is quite a fundamental issue at play here relating to the implementation of checkAndMutate that checks against a null value. I was trying to figure out what HBase does.  From the docs in the Table interface:

> "If the passed value is null, the check is for the lack of column (ie: non-existance)"

HBase ignores the CompareOperator completely and always assumes that any `null` value means a non-existence check.  That's a bit counter intuitive if someone uses `CompareOp.NOT_EQUALS`, or really anything but `CompareOp.EQUALS` because HBase will always check for `non-existence` and ignore the CompareOperator.

In the CBT client, we implemented `EQUALS null` means non-existence and `NOT_EQUALS null` means existence.  I don't think that we can implement the HBase implementation exactly due to historical translation of `NOT_EQUALS null` to mean `existence`.  However, we can add a clause that all CompareOperators except `NOT_EQUALS` mean `non-existence`.

To make this a bit more complicated, HBase 2.0 introduced a new CheckAndMutateBuilder that has a `ifNotExists()` method.  It also has an `ifMatches(CompareOperator op, byte[] value)` method that will throw an exception if the value is null.  We probably should enforce HBase's semantics in any new HBase2 methods and give enough information about how to fix the problem in the exception message.

Existence can probably be checked with `ifMatches(CompareOperator.GREATER, EMPTY_BYTES)`, but I'll confirm that.  If so, I'll implement HBase 2.0 that way.
