### ISSUE TITLE
Use grpc version 1.10.1

### ISSUE THREAD

**Issue by rpeng** [GoogleCloudPlatform/cloud-bigtable-client#1756]
Currently grpc 1.10.0 is affected by https://github.com/grpc/grpc-java/pull/4027, where we run into UnresolvedAddressException when setting GRPC_PROXY_EXP. It seems to be fixed in grpc version 1.10.1 - is it possible to make a release with the new grpc version?

**Comment by sduskis** [comment]
Thanks for the update.  We'll make a new release next week.

**Comment by sduskis** [comment]
@pawan-qlogic, can you please try to perform the upgrade and run all of our tests?

**Comment by pawan-qlogic** [comment]
Upraded grpc version, all the test cases were successfully performed. Pull request created.

**Comment by sduskis** [comment]
PR #1763 fixed this.

**Comment by sduskis** [comment]
I'm going to keep this open until a new release is made.

**Comment by plelevier** [comment]
Hello, 
When using google-cloud-java, it seems that they have not released any version with grpc 1.10.0  : 
https://github.com/GoogleCloudPlatform/google-cloud-java/blob/v0.42.0/pom.xml
https://github.com/GoogleCloudPlatform/google-cloud-java/blob/v0.42.1/pom.xml

The problem is when mixing cloud-bigtable-client 1.3.0 and google-cloud-java, maven raise a conflict between grpc 1.10.0 and 1.10.1. 
I've been able to force grpc dependencies to 1.10.1 but it is a little bit ugly and it may lead to setup problems with google libs to newcomers.

It would be great that the dependencies of cloud-bigtable-client were following the dependencies used in google-cloud-java (ie, never use some grpc version that was never referenced in google-cloud-java)

**Comment by sduskis** [comment]
@plelevier: We're working on it.  Hopefully the next release will sync up all of the relevant versions. I'm hoping to depend on some of the core google-cloud-java artifacts via the [google-cloud-java BOM](https://github.com/GoogleCloudPlatform/google-cloud-java/tree/master/google-cloud-bom) to ensure that everything is in sync.

**Comment by plelevier** [comment]
Great solution, thank you

**Comment by sduskis** [comment]
We aim to make a release sometime early next week.  We have a couple things to do before the release.
