### ISSUE TITLE
ChannelPool: least outstanding request algorithm

### ISSUE THREAD

**Issue by sduskis** [GoogleCloudPlatform/cloud-bigtable-client#1773]
Our `ChannelPool` uses a round-robbin approach to selecting a `Channel`.  It's effective in most cases, but may cause problems in other cases.   A user found that one channel was slow and overloaded and caused various problems a "least outstanding request algorithm" will reduce problems like theirs in the future.

**Comment by eiiches** [comment]
Hi,
I've been in contact with the Japanese support team about the issue.

Here's my implementation of the algorithm: https://github.com/eiiches/cloud-bigtable-client/commits/feature/least-outstanding-requests-balancing-channel-pool

We've load-tested the implementation, and it worked well, but I'm still worried that there may be some corner case that the number of outstanding requests is not correctly incr/decremented.

I can open a PR if you like, but it will probably take some time to sign a Corporate CLA. So I'd also be glad if someone can implement it independently.

All that said, I believe these kind of load balancing algorithms should be ideally provided by gRPC modules to avoid re-implementing it everywhere.

**Comment by igorbernstein2** [comment]
Hi eiiches,

Thanks for sharing! I've sketched out an alternative approach here: https://github.com/GoogleCloudPlatform/cloud-bigtable-client/pull/1774.

It should have a lower overhead to maintaining an ordered list of loaded connections while evenly spreading the load across the pool.

Also, GRPC actually has native [load balancing ](https://github.com/grpc/grpc/blob/master/doc/load-balancing.md), which we will switch to at some point in the future.

**Comment by eiiches** [comment]
Wow, I like your approach! I'll switch to your implementation when it gets merged.
Thanks!

**Comment by steveniemitz** [comment]
To chime in here, I recently spent time debugging a very-high p9999 latency in our requests.  We've been at a limited-load launch, so our QPS to bigtable has been fairly low and spread across a lot of instances of our service.  It turns out the QPS was so low that our connections would be closed due to inactivity by our outgoing NAT devices.

My solution was to simply reduce the data channel count to 1, but thats not great because now I need to remember to increase it (maybe?) as we ramp up traffic.

A cool solution might be to build a pool that dynamically expands/contracts based on the exponential moving average of the load over the channels.

**Comment by sduskis** [comment]
I've had similar thoughts about auto-tuning Channel Pools.  The gRPC team is working on their own implementation of Channel Pools, which is likely to be better than anything we develop specifically for Cloud Bigtable.  The Channel Pool implementation is different from the Load Balancing feature of gRPC that @igorbernstein2 mentioned

**Comment by sduskis** [comment]
The gRPC team is going to continue to work on this.  We'll use their pooling mechanism when it's ready.
