### ISSUE TITLE
Add better support for using CloudBigtableIO in a Dataflow template

### ISSUE THREAD

**Issue by kylehendricks** [GoogleCloudPlatform/cloud-bigtable-client#2028]
We are currently using `CloudBigtableIO` to do a scheduled scan of a bigtable.  To do this we use [Dataflow Templates](https://cloud.google.com/dataflow/docs/guides/templates/overview).  It seems that in order for this to work right, `CloudBigtableIO` would need to support passing in `ValueProvider`'s for configuration.

Currently when trying to upload a "dataflow template" that uses `CloudBigtableIO`, it is making a connection to bigtable when the `getEstimatedSizeBytes` method gets called which will work when run locally since the gcloud credentials are there but fails when building in CI. This doesn't actually fail the template upload but is causing some long delays in CI.

I apologize if this doesn't make much sense, still wrapping my head around Dataflow.

**Comment by sduskis** [comment]
Are you creating your own dataflow job?  If so, it might just be simpler to schedule a maven command line, or running a java command rather than creating a Template.

I don't have a great understanding of templates, but I do understand that `getEstimatedSizeBytes` is run earlier than other Beam methods.  I don't have a great answer for you about your CI problem, because I don't completely understand your deployment environment, nor do I have insights into the behavior of Dataflow Templates relating to `getEstimatedSizeBytes`.   Perhaps you can use a json service account in your CI?

**Comment by kylehendricks** [comment]
Yea.  It's starting to seem like the only point of templates are to allow kicking off dataflow's without needing the JRE and the actual dataflow jar.  For us that is super handy but it does seem like lot of beam sources and sinks don't play well with the idea.

We will probably try to get away from using templates as they seem to be a pain and not well supported.
