### ISSUE TITLE
Setting DataHost is not possible in DataFlow

### ISSUE THREAD

**Issue by derjust** [GoogleCloudPlatform/cloud-bigtable-client#484]
Setting the `DataHost` is not possible in DataFlow:
`CloudBigtableConfiguration` and derived class do not provide such a field.
The methods 
`com.google.cloud.bigtable.dataflow.CloudBigtableConfiguration.toBigtableOptions()` and `com.google.cloud.bigtable.dataflow.CloudBigtableConfiguration.toHBaseConfig()` do not set the required property. 
Even adding it there seems to be ignored.

Only changing `com.google.cloud.bigtable.config.BigtableOptions.BIGTABLE_DATA_HOST_DEFAULT` has the desired effect - which requires a binary release of a custom build of this library just to use a different data host (i.e. for testing or load testing)

**Comment by sduskis** [comment]
What's the context that you're trying to set the host in?  Is it a read or write?

**Comment by derjust** [comment]
Both :-)
We discovered it while testing a pure PUT/Ingestion workflow.
But a Scan/PUT workflow is around the corner, too.

**Comment by sduskis** [comment]
In most cases, overriding data host shouldn't be required, so I think that we need to use a custom solution here.

You probably need to create a subclass of CloudBigtableConfiguration, or more likley CloudBigtableScanConfiguration, and override toHBaseConfig().

Instead of calling writeToTable(), we'll try this:
 new CloudBigtableWriteTransform<>(new CloudBigtableMultiTableWriteFn([YourConfigObject]));

I'll add a new writeTo() method that will allow you to do that, but it's also something you can do yourself.

You should also pass YourConfigObject which subclasses CloudBigtableScanConfiguration into the read(CloudBigtableScanConfiguration config) method.

**Comment by sduskis** [comment]
Closing this.  The solution in #487 was deemed to be a better alternative than my suggestion here.
